databases:
  - name: mysitedb
    plan: free
    databaseName: vital
    user: ogata

services:
  - type: web
    plan: free
    name: healthcareapp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn healthcareapp.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4